#!/bin/bash
docker build -t build-geth .
docker run --rm -v "$PWD":/shared/ -w /projects/src/github.com/ethereum/go-ethereum/cmd/geth build-geth bash -c "CC=arm-linux-gnueabi-gcc-4.7 GOARCH=arm CGO_ENABLED=1 godep go install -v && cp /projects/bin/linux_arm/geth /shared/"
